
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-18T14:06:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "516ae1969ea4da36cc1d5d13e3efd908d1f49507",
 "version": "1!1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
